server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      cookie:
        name: sentinel_dashboard_cookie
spring:
  application:
    name: macula-cloud-sentinel

auth:
  filter:
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
  password: sentinel
  username: sentinel

sentinel:
  dashboard:
    version: '1.8.6'
  datasource:
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: SENTINEL

logging:
  file:
    name: ${user.home}/logs/csp/sentinel-dashboard.log
  level:
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

